### ISSUE TITLE
Create ROCK for storage-initialiser for CKF 1.7

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/kserve-rocks#11]
### What needs to get done

1. Create the `rockcraft.yaml` file
4. Copy our CI automation for building the image on every PR and when a PR is merged

### Why it needs to get done

In order for us to have our own built OCI Image for that component

**Comment by NohaIhab** [comment]
We hit an issue with building the ROCK where the args for the container were not passed to the Pebble service correctly.
The `storage-initializer` image is used as an `initContainer` for `inferenceService` Pods, so the container is started by the Kserve container with arguments passed to it:
```
  initContainers:
  - args:
    - gs://kfserving-examples/models/sklearn/1.0/model
    - /mnt/models
    image: storage-initializer_v0.10.0-22.04-1_amd64:rock
    imagePullPolicy: IfNotPresent
    name: storage-initializer
```
the initContainer was then failing with:
```
message: |
          error: unknown command "gs://kfserving-examples/models/sklearn/1.0/model", see 'pebble help'
```
It was not possible in the past to pass arguments to Pebble within a rock, but thanks to the rockcraft team's [update](https://github.com/canonical/rockcraft/issues/382#issuecomment-1844912142), we can now do it.
PR is now open.
