### ISSUE TITLE
pmmlserver v0.10.0 cant add arguments dynamically to command in service 

### ISSUE THREAD

**Issue by misohu** [canonical/kserve-rocks#6]
Our newest `track/v0.10.0` pmmlserver rock uses miniconda to install python dependencies and to run the workload because of that we had to run the rock `service` section like this 

```
services:
  pmml-server:
    override: replace
    summary: "Pmml server service"
    startup: enabled
    command: bash -c 'export PATH=/opt/conda/bin/:${PATH} && eval $(/opt/conda/bin/conda shell.bash hook 2> /dev/null) && source /opt/conda/etc/profile.d/conda.sh && conda activate && python -m pmmlserver'
    environment:
      PYTHONPATH: /pmmlserver:/kserve
```

This command section makes it impossible to pass arguments to the command section. We need this because when kserve workloads are scheduled the container section looks like this:

```
containers:
  - args:
    - --model_name=pmml-demo
    - --model_dir=/mnt/models
    - --http_port=8080
    image: misohu/pmmlserver:v0.10.0_22.04_1
    imagePullPolicy: IfNotPresent
```

In the command section we need to run `bash -c` because we want to activate and setup the conda environment in the container. The the way how can be the env variables values resolved.

**Comment by misohu** [comment]
I have tried to rewrite the rock using just python without miniconda, so I overcome the problem of activating the virtual environment. The key parts looks like this.

```
services:
  pmml-server:
    override: replace
    summary: "Pmml server service"
    startup: enabled
    command: python3.10 -m pmmlserver
    environment:
      PYTHONPATH: /pmmlserver:/kserve

parts:
  python:
    plugin: nil
    source: https://github.com/kserve/kserve.git
    source-subdir: python
    source-tag: v0.10.0
    build-packages:
    - python3.10
    overlay-packages:
    - openjdk-11-jdk
    - python3.10
    - python3.10-distutils
    - python3-setuptools
    override-build: |
      cd python
      pip3 install --no-cache-dir --upgrade pip
      pip3 install -e ./kserve
      pip3 install --no-cache-dir -e ./pmmlserver

      cp -fr pmmlserver $CRAFT_PART_INSTALL/pmmlserver
      cp -fr kserve $CRAFT_PART_INSTALL/kserve

      mkdir -p $CRAFT_PART_INSTALL/usr/local/lib/python3.10/dist-packages
      cp -fr /usr/local/lib/python3.10/dist-packages/* $CRAFT_PART_INSTALL/usr/local/lib/python3.10/dist-packages/
```

This works and makes the image executable. The problem is with passing arguments from Pod to the container as mentioned bellow: 

```
containers:
  - args:
    - --model_name=pmml-demo
    - --model_dir=/mnt/models
    - --http_port=8080
    image: misohu/pmmlserver:v0.10.0_22.04_1
    imagePullPolicy: IfNotPresent
 ```
 
This will end up sending `--model_name --model_dir --http_port` to Rock's entrypoint which is pebble. Meaning the args won't be passed to pmml-service. This is the way how you can send args directly to pmml-server service in pebble default entrypoint: 
 
 ```
 docker run misohu/pmmlserver:v0.10.0_22.04_1 --args pmml-server --model_name=pmml-demo
 ```
 
 However we would have to change the upstream pod's specification to pass the ars like that. 
 
 After talking to @SamirPS there is no way right now to pass args directly to the `pmml-service`.
